Enable ingress routing and onboard meavk/imdb-ui

diff --git a/cli/.kic/commands/build/imdb b/cli/.kic/commands/build/imdb
--- a/cli/.kic/commands/build/imdb
+++ b/cli/.kic/commands/build/imdb
@@ -7,6 +7,7 @@ cd "$REPO_BASE" || exit
 
 # validate directories
 if [ ! -d /workspaces/imdb-app ]; then echo "/workspaces/imdb-app directory not found. Please clone the imdb-app repo to /workspaces"; exit 1; fi
+if [ ! -d /workspaces/imdb-ui ]; then echo "/workspaces/imdb-ui directory not found. Please clone the imdb-ui repo to /workspaces"; exit 1; fi
 if [ ! -d deploy ]; then echo "$REPO_BASE/deploy directory not found. Please cd to an appropriate directory"; exit 1; fi
 if [ ! -d deploy/apps ]; then echo "$REPO_BASE/deploy/apps directory not found. Please cd to an appropriate directory"; exit 1; fi
 if [ ! -d deploy/apps/imdb ]; then echo "$REPO_BASE/deploy/apps/imdb directory not found. Please cd to an appropriate directory"; exit 1; fi
@@ -16,17 +17,23 @@ if [ ! -d deploy/apps/webv ]; then echo "$REPO_BASE/deploy/apps/webv directory n
 kubectl delete -f deploy/apps/webv --ignore-not-found=true --wait=false
 kubectl delete -f deploy/apps/imdb --ignore-not-found=true --wait=false
 
-# build and push the local image
+# build and push the local image for imdb-app
 docker build /workspaces/imdb-app -t k3d-registry.localhost:5500/imdb-app:local
 docker push k3d-registry.localhost:5500/imdb-app:local
 
+# build and push the local image for imdb-ui
+docker build /workspaces/imdb-ui/src/Imdb.BlazorWasm -t k3d-registry.localhost:5500/imdb-ui:local
+docker push k3d-registry.localhost:5500/imdb-ui:local
+
 # wait for delete to finish
 kubectl wait pod -l app=webv -n imdb --for delete --timeout=30s
-kubectl wait pod -l app=imdb -n imdb --for delete --timeout=30s
+kubectl wait pod -l app=imdb-api -n imdb --for delete --timeout=30s
+kubectl wait pod -l app=imdb-ui -n imdb --for delete --timeout=30s
 
 # deploy local app and re-deploy webv
 kubectl apply -f deploy/apps/imdb
-kubectl wait pod -l app=imdb -n imdb --for condition=ready --timeout=30s
+kubectl wait pod -l app=imdb-api -n imdb --for condition=ready --timeout=30s
+kubectl wait pod -l app=imdb-ui -n imdb --for condition=ready --timeout=30s
 kubectl apply -f deploy/apps/webv
 kubectl wait pod -l app=webv -n imdb --for condition=ready --timeout=30s
 
